// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductMicroservice.Data;

#nullable disable

namespace ProductMicroservice.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230426184833_addedProductStatus")]
    partial class addedProductStatus
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProductMicroservice.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            CategoryName = "MusicNFT",
                            Description = "Music NFT"
                        },
                        new
                        {
                            CategoryID = 2,
                            CategoryName = "GenerativeNFT",
                            Description = "Generative NFT"
                        },
                        new
                        {
                            CategoryID = 3,
                            CategoryName = "DigiArtNFT",
                            Description = "DigiArt NFT"
                        },
                        new
                        {
                            CategoryID = 4,
                            CategoryName = "CollectablesNFT",
                            Description = "Collectables NFT"
                        });
                });

            modelBuilder.Entity("ProductMicroservice.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int?>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageBase64")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<double?>("UnitPrice")
                        .HasColumnType("float");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryID = 1,
                            CreatedBy = "",
                            Description = "",
                            ImageBase64 = "nft1.webp",
                            ProductName = "nft1",
                            Status = 0,
                            UnitPrice = 20.0
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryID = 2,
                            CreatedBy = "",
                            Description = "",
                            ImageBase64 = "nft2.webp",
                            ProductName = "nft2",
                            Status = 0,
                            UnitPrice = 50.0
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryID = 3,
                            CreatedBy = "",
                            Description = "",
                            ImageBase64 = "nft3.webp",
                            ProductName = "nft3",
                            Status = 0,
                            UnitPrice = 55.0
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryID = 4,
                            CreatedBy = "",
                            Description = "",
                            ImageBase64 = "nft4.webp",
                            ProductName = "nft4",
                            Status = 0,
                            UnitPrice = 30.0
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryID = 1,
                            CreatedBy = "",
                            Description = "",
                            ImageBase64 = "nft5.webp",
                            ProductName = "nft5",
                            Status = 0,
                            UnitPrice = 20.0
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryID = 2,
                            CreatedBy = "",
                            Description = "",
                            ImageBase64 = "nft6.webp",
                            ProductName = "nft6",
                            Status = 0,
                            UnitPrice = 10.0
                        },
                        new
                        {
                            ProductId = 7,
                            CategoryID = 3,
                            CreatedBy = "",
                            Description = "",
                            ImageBase64 = "nft7.webp",
                            ProductName = "nft7",
                            Status = 0,
                            UnitPrice = 20.0
                        },
                        new
                        {
                            ProductId = 8,
                            CategoryID = 4,
                            CreatedBy = "",
                            Description = "",
                            ImageBase64 = "nft8.jpg",
                            ProductName = "nft8",
                            Status = 0,
                            UnitPrice = 20.0
                        },
                        new
                        {
                            ProductId = 9,
                            CategoryID = 1,
                            CreatedBy = "",
                            Description = "",
                            ImageBase64 = "nft9.webp",
                            ProductName = "nft9",
                            Status = 0,
                            UnitPrice = 25.0
                        },
                        new
                        {
                            ProductId = 10,
                            CategoryID = 2,
                            CreatedBy = "",
                            Description = "",
                            ImageBase64 = "nft10.webp",
                            ProductName = "nft10",
                            Status = 0,
                            UnitPrice = 30.0
                        },
                        new
                        {
                            ProductId = 11,
                            CategoryID = 3,
                            CreatedBy = "",
                            Description = "",
                            ImageBase64 = "nft11.webp",
                            ProductName = "nft11",
                            Status = 0,
                            UnitPrice = 40.0
                        },
                        new
                        {
                            ProductId = 12,
                            CategoryID = 4,
                            CreatedBy = "",
                            Description = "",
                            ImageBase64 = "nft12.webp",
                            ProductName = "nft12",
                            Status = 0,
                            UnitPrice = 20.0
                        },
                        new
                        {
                            ProductId = 13,
                            CategoryID = 1,
                            CreatedBy = "",
                            Description = "",
                            ImageBase64 = "nft13.webp",
                            ProductName = "nft13",
                            Status = 0,
                            UnitPrice = 30.0
                        },
                        new
                        {
                            ProductId = 14,
                            CategoryID = 2,
                            CreatedBy = "",
                            Description = "",
                            ImageBase64 = "nft14.webp",
                            ProductName = "nft14",
                            Status = 0,
                            UnitPrice = 50.0
                        },
                        new
                        {
                            ProductId = 15,
                            CategoryID = 3,
                            CreatedBy = "",
                            Description = "",
                            ImageBase64 = "nft15.webp",
                            ProductName = "nft15",
                            Status = 0,
                            UnitPrice = 20.0
                        },
                        new
                        {
                            ProductId = 16,
                            CategoryID = 4,
                            CreatedBy = "",
                            Description = "",
                            ImageBase64 = "nft16.webp",
                            ProductName = "nft16",
                            Status = 0,
                            UnitPrice = 20.0
                        },
                        new
                        {
                            ProductId = 17,
                            CategoryID = 1,
                            CreatedBy = "",
                            Description = "",
                            ImageBase64 = "nft18.webp",
                            ProductName = "nft18",
                            Status = 0,
                            UnitPrice = 20.0
                        },
                        new
                        {
                            ProductId = 18,
                            CategoryID = 2,
                            CreatedBy = "",
                            Description = "",
                            ImageBase64 = "nft19.webp",
                            ProductName = "nft19",
                            Status = 0,
                            UnitPrice = 20.0
                        },
                        new
                        {
                            ProductId = 19,
                            CategoryID = 3,
                            CreatedBy = "",
                            Description = "",
                            ImageBase64 = "nft20.webp",
                            ProductName = "nft20",
                            Status = 0,
                            UnitPrice = 20.0
                        },
                        new
                        {
                            ProductId = 20,
                            CategoryID = 4,
                            CreatedBy = "",
                            Description = "",
                            ImageBase64 = "nft21.webp",
                            ProductName = "nft21",
                            Status = 0,
                            UnitPrice = 20.0
                        },
                        new
                        {
                            ProductId = 21,
                            CategoryID = 1,
                            CreatedBy = "",
                            Description = "",
                            ImageBase64 = "nft17.webp",
                            ProductName = "nft17",
                            Status = 0,
                            UnitPrice = 28.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
